#define introduction 1200
#define gettingstarted 1300
#define moreresources 1400
#define additionalhelp 150
#define changingorganizationinformation 2100
#define seaturtlelist 140
#define addingseaturtleinformation 3100
#define seaturtleinformationscreen 90
#define seaturtleinformationscreentags 110
#define taginformationscreen 120
#define seaturtleinformationscreenmorphometrics 6140
#define morphometricinformationscreen 6150
#define seaturtleinformationscreenattachments 6190
#define seaturtleinformationscreenbrochure 6200
#define holdingtanks 4100
#define holdingtankinformationscreen 130
#define watermeasurements 4200
#define modifyinghatchlingeventinformation 6050
#define hatchlingsacquiredeventscreen 6060
#define hatchlingsdiedeventscreen 6070
#define hatchlingsreleasedeventscreen 6080
#define hatchlingsdoeeventscreen 6160
#define modifyingwashbackeventinformation 6090
#define washbacksacquiredeventscreen 6100
#define washbacksdiedeventscreen 6110
#define washbacksreleasedeventscreen 6120
#define washbacksdoaeventscreen 6180
#define printingblankforms 5002
#define fillingoutreportsandforms 5005
#define seaturtleholdingfacilityquarterlyreport 5010
#define marineturtlecaptivefacilityquarterlyreportforhatchlings 5020
#define marineturtlecaptivefacilityquarterlyreportforwashbacks 6130
#define beachrestorationprojectmonitoringtable 5030
#define disorientationincidentform 5040
#define educationalpresentationsusingliveseaturtles 5050
#define necropsyreportform 5060
#define nighttimepublichatchlingreleaseform 5070
#define papillomadocumentationform 5080
#define publicturtlewatchform 5090
#define strandingandsalvageform 5100
#define tagrequestform 5110
#define taggingdataform 5120
#define turtletransferform 5130
#define printingotherreports 6010
#define turtleinjuryreport 6020
#define turtletagreport 6030
#define hatchlingsandwashbacksbycountyreport 6170
#define adminfunctionsmenu 6210
#define masterfilescounty 6220
#define latitudelongitudehelper 6230
#define enduserlicenseagreement 1100

